# Generated by Django 5.1.1 on 2024-10-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_view_counter_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Укажите есть ли на складе', verbose_name='Наличие в продаже'),
        ),
    ]
